
import Head from 'next/head';
import React from 'react'
import Contact from '../components/Contact'
import Hero from '../components/Hero'

const contact = () => {
  return (
    
    <div>   
       <Head>
    <title>Photography - Contact</title>
    <meta name='description' content='Generated by create next app | photography' />
    <link rel='icon' href='/favicon.ico' />
    </Head>

    
        <Hero heading='Contact' message='Submit the form below for more work and quotes.' />
        <Contact />
    </div>
  )
}

export default contact